### PR TITLE
Cannot import battery shield fzfp 

### PR DESCRIPTION
**Pull request by barde**
Something commented out the width and height in the fzfp file. I rebuild it and now its working.

### CODE REVIEW

**Comment by mcauser** [comment]
Sorry about that. Accidental commit. Fixed at 0904b9abe9f92577c191db691a6f1b0154ea5b75

**Comment by barde** [comment]
Sure! Never trust random stranger's compilation. ;)

**Comment by mcauser** [comment]
There is a build.sh script in the root that both compiles them and puts a copy in the demo sketch :)

**Comment by barde** [comment]
Aww... And I was fighting with Fritzing to get this pull request done. Nonetheless, thank you for the great parts! Already used them in my [bfc3000](https://github.com/barde/bfc3000).

**Comment by mcauser** [comment]
Interesting project. V3 Raspberry Pi with camera and bird song recording for species detection? MicroPython is now working on the WeMos D1 Mini. If you can program in Python, you might find it nicer to work with than Arduino IDE or NodeMCU

**Comment by barde** [comment]
Species detection is planned for V2. I wanted to try the neural network of the Arduino 101 but they haven't released the libraries for it, yet.

Nonetheless, there are only [great tits](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Great_Tit_%28Parus_major%29_1.jpg/800px-Great_Tit_%28Parus_major%29_1.jpg) bold enough to use the current feeding station which is used for bfc3000. I placed it behind some cover after moving it slightly every day from plain sight and the birds remembered the position - other species won't come near nor are they able to see the bird feed station.

Python is always nice to use but I have some doubts about its performance and power consumption. The project's aim is to be as low power as possible. I wonder if pyBrain runs on MicroPython with sufficient speed...

**Pull request closed without merging**
